[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  nmap <Space> [unite]
  nnoremap <silent> [unite]a :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
  nnoremap <silent> [unite]b :<C-u>Unite<Space>buffer<CR>
  nnoremap <silent> [unite]g :<C-u>Unite<Space>grep<CR>
  nnoremap <silent> [unite]r :<C-u>UniteResume -buffer-name=search-buffer<CR>
  nnoremap <silent> [unite]w :<C-u>Unite<Space>grep:. -buffer-name=search-buffer<CR><C-R><C-W><CR>
  let g:unite_source_grep_command = 'ag'
  let g:unite_source_grep_default_opts = '--nogroup --nocolor --column'
  let g:unite_source_grep_recursive_opt = ''
  call unite#custom#source('file',  'matchers',  "matcher_default") " ドットファイル表示
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nnoremap <silent> <space><space>a :<C-u>Denite -mode=normal file_rec<CR>
  nnoremap <silent> <space><space>b :<C-u>Denite -mode=normal file_mru<CR>
  nnoremap <silent> <space><space>g :<C-u>Denite -mode=normal grep<CR>
  nnoremap <silent> <space><space>w :<C-u>DeniteCursorWord -mode=normal grep<CR>
  nnoremap <silent> <space><space>y :<C-u>Denite -mode=normal neoyank<CR>
'''
hook_post_source = '''
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
  let g:auto_save = 1
  let g:auto_save_in_insert_mode = 0
  let g:auto_save_silent = 1
'''

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
